name: Build ios nosign

on:
  push:
    tags:
      - v*ios


jobs:
  Build_ios_nosign:
    name: Build ios nosign
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Flutter action
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Flutter pub get
        run: flutter pub get

      - name: Build resolve Swift dependencies
        run: xcodebuild -resolvePackageDependencies -workspace ios/Runner.xcworkspace -scheme Runner -configuration Release

      - name: Build ios
        run: flutter build ios --release --no-codesign

      - name: Build ipa
        run: |
          cd build
          mkdir -p Payload
          mv ios/iphoneos/Runner.app Payload
          zip -9 Runner.ipa -r Payload
      - name: Publish iOS Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-ios-nosign
          path: build/Runner.ipa